# Generated by Django 4.2.2 on 2023-06-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="order",
        ),
    ]
